/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LAMPORT_H_RPCGEN
#define _LAMPORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct BAKERY {
	int id;
	int num;
	char symb;
};
typedef struct BAKERY BAKERY;

#define BAKERY_PROG 0x2000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NUM 1
extern  struct BAKERY * get_num_1(struct BAKERY *, CLIENT *);
extern  struct BAKERY * get_num_1_svc(struct BAKERY *, struct svc_req *);
#define GET_RES 2
extern  struct BAKERY * get_res_1(struct BAKERY *, CLIENT *);
extern  struct BAKERY * get_res_1_svc(struct BAKERY *, struct svc_req *);
#define WAIT_RES 3
extern  struct BAKERY * wait_res_1(struct BAKERY *, CLIENT *);
extern  struct BAKERY * wait_res_1_svc(struct BAKERY *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NUM 1
extern  struct BAKERY * get_num_1();
extern  struct BAKERY * get_num_1_svc();
#define GET_RES 2
extern  struct BAKERY * get_res_1();
extern  struct BAKERY * get_res_1_svc();
#define WAIT_RES 3
extern  struct BAKERY * wait_res_1();
extern  struct BAKERY * wait_res_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BAKERY (XDR *, BAKERY*);

#else /* K&R C */
extern bool_t xdr_BAKERY ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LAMPORT_H_RPCGEN */
