/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include "stdio.h"
#include "stdlib.h"

void calculator_prog_1(char *host)
{
	CLIENT *clnt;
	clnt = clnt_create(host, CALCULATOR_PROG, CALCULATOR_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}

	struct CALCULATOR  *result_1;
	struct CALCULATOR  calculator_proc_1_arg;
	calculator_proc_1_arg.arg1 = 2.0f;
	calculator_proc_1_arg.arg2 = -5.5f;
	calculator_proc_1_arg.op = MUL;

	result_1 = calculator_proc_1(&calculator_proc_1_arg, clnt);
	if (result_1 == NULL)
		clnt_perror(clnt, "call failed:");
	else
		printf("result: %f", result_1->result);

	clnt_destroy( clnt );
}


int main(int argc, char** argv)
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	calculator_prog_1( host );
}
